### ISSUE TITLE
Peek menu not showing on Genesis

### ISSUE THREAD

**Issue by cognitivegears** [mrsonicblue/peek#2]
For some reason, the Peek menu is not showing up for the Genesis core. It is the only core I haven't seen it for yet. I do have a lot of files in Genesis, and the contents are all zip files, not sure if either of these make a difference. Please let me know if there is any debugging or other info I can provide.

**Comment by cognitivegears** [comment]
I think I was able to track down the issue. In fact, on the Genesis they weren't still zipped, but instead a directory for each file. And I found another core (NES) that I had all directories at the root level and Peek doesn't show up there either. It looks like there maybe needs to be at least one file in the root level for Peek to show up.

**Comment by cognitivegears** [comment]
Ok - so I was wrong on the original issue. As it turns out, Peek does show up on the Genesis core. The problem was, I have a ton of zip files in there, and since zip files show as directories, Peek was getting sorted into the middle of them. For most cores it's at the top because directories are sorted before files. Is it possible to change the name to "~ Peek" or something else that is going to sort at the top of the list?

**Comment by mrsonicblue** [comment]
The tilde (~) would cause it to sort to the very end. It would need to be a character between space and zero in the ASCII table that is also allowed as a filename and without special meaning. For example: a slash (/) is illegal and a dot (.) has special meaning. Maybe a dash (-) would be best?

Check out: http://www.asciitable.com/

**Comment by cognitivegears** [comment]
Thanks for taking a look at this! Certainly up to you, but here's a couple of ideas based on that list:

!Peek

Not sure it's my favorite, but that's the lowest in order so most likely to be sorted early

###Peek###

Early in the list and visually catchy, maybe my favorite

(Peek)

Would parens be special? Looks the best to me though higher in the list.

**Comment by cognitivegears** [comment]
Should be fixed with Pull Request #8
