### ISSUE TITLE
Feature request: further ideas for edit functionality

### ISSUE THREAD

**Issue by cognitivegears** [mrsonicblue/peek#3]
The menu based edit functionality works great, but now that I've been using it for a bit there are a couple of further ideas that I think would make it even better if they are possible:

After selecting "~ MANAGE DATA", you are taking to a full ROM list. For some people this list can be pretty long :) - I wonder if it wouldn't make sense to have this listing instead have one more level that shows the alphabetical A-Z display, that way it's easier to jump to a title that you want to manage?

Also, after selecting a title in that screen, it may be useful to have an additional "Play" option if that is a possibility? I find myself wanting to go through the ROM list straight from the manage data section and pick my favorites, etc; but generally I need to play them at least once to make sure that the ROM is working and that it's the one I'm thinking of. While you can jump back and forth in the menus, it takes quite a while to go through all the ROMS in some cores that way, may be faster if it can all be done from manage itself while you are selecting favorites.

**Comment by mrsonicblue** [comment]
I'm going to split this into two separate issues. I'd consider the "play" option to be a higher priority than the A-Z folders.
